## 
# Makefile example: Print an onboard checklist of real-world to-do tasks.
##
.PHONY: onboard-checklist
onboard-checklist:
	$(info Onboard tasks for you to do before you continue:)
	$(info - [ ] Get your organization email address, then read your email)
	$(info - [ ] Get your organization GitHub username, then read our GitHub page)
	$(info - [ ] Get your organization macOS user account, then update your system)
