## 
# Makefile example: Print an onboard checklist of real-world to-do tasks.
##
.PHONY: onboard-checklist
onboard-checklist:
	$(info Onboard tasks for you to do before you continue:)
	$(info - [ ] Get your organization email address, then read your email messages.)
	$(info - [ ] Join our Discord for chat, then visit the channel #onboard and say hi.)
	$(info - [ ] Join our Linear for tasks, then create any task that helps us improve.)
	$(info - [ ] Join our Figma for UI/UX, then see project name "onboard" and learn it.)
	$(info - [ ] Create a fresh computer system user account, then do any system updates.)
	$(info - [ ] Get your GitHub account, then view our GitHub organization page.)
	$(info - [ ] Get your Amazon Web Services account, then sign in with AWS IAM SSO.)
